editor: MateoM
date: 2019/06/07
ver: 1.1
device: smartsensor
resistor: 
  id: ID vishay
  resistance: 22000
  tolerance: 5
  betta: 3740
  bettaTolerance: 2
shunt: 
  id: ID shunt
  resistance: 10000
  tolerance: 1
adc:
  id: ads1256
  sps:
#    - "30000":"0"
#    - "15000":"1"
#    - "75000":"2"
    - 3750: &def_sps 3  #default value
    - 2000: 4
    - 1000: 5
    - 500: 6
    - 100: 7
    - 50: 9
    - 30: 10
    - 25: 11
    - 15: 12
    - 10: 13
    - 5: 14
    - 2.5: 15
  zeff:
    - 10000000
    - 10000000
    - 10000000
    - 10000000
    - 10000000
    - 20000000
    - 40000000
    - 40000000
    - 40000000
    - 80000000
    - 80000000
    - 80000000
    - 80000000
    - 80000000
    - 80000000
    - 80000000
  fclkin: 768000000
  refVoltage:
    id: "ID zener"
    voltage: 2.5
    #tolerance:
aquisition:
    numberOfsps: &def_nsps 1000 #default value 
    sleepTime: &def_sleep 5000  #default value
powerSource:
  voltage: 3.3
  #maxCurrent:
  settlingtime: 47000e-6
default:
  sps: *def_sps
  nsps: *def_nsps
  sleep: *def_sleep
