editor: MateoM
date: 2020/04/21
device: smartsensor
database:
  ntcresistor: 
    id: &id_ntc ID vishay
    resistance: 22000
    tolerance: 5
    betta: 3740
    bettaTolerance: 2
  shunt: 
    id: &id_shunt ID shunt
    resistance: 10000
    tolerance: 1
  adc: 
    id : &id_adc ADS1256
    impedance: [10000000, # reset the default values
      10000000,
      10000000,
      10000000,
      10000000,
      20000000,
      40000000,
      40000000,
      40000000,
      80000000,
      80000000,
      80000000,
      80000000,
      80000000,
      80000000,
      80000000 ]
    samplingSpeed: [&def_speed 'ADS1256_30000SPS' 
    ,'ADS1256_15000SPS'
    ,'ADS1256_7500SPS'
    ,'ADS1256_3750SPS'
    ,'ADS1256_2000SPS'
    ,'ADS1256_1000SPS'
    ,'ADS1256_500SPS'
    ,'ADS1256_100SPS'
    ,'ADS1256_60SPS'
    ,'ADS1256_30SPS'
    ,'ADS1256_50SPS'
    ,'ADS1256_25SPS'
    ,'ADS1256_15SPS'
    ,'ADS1256_10SPS'
    ,'ADS1256_5SPS'
    ,'ADS1256_2d5SPS']
    clockFreq: 768000000
  refvoltage: 
    id: &id_refvoltage zenner
    voltage: 2.5
    #tolerance:
  powersuply:
    id: &id_power kinez
    voltage: 3.3
    #maxCurrent:
    settlingtime: 47000e-6    
  activeconfiguration:
    ntcresistor: *id_ntc
    shunt: *id_shunt
    powersuply: *id_power
    adc: *id_adc
    refvoltage: *id_refvoltage
    numberofsamples: 100
    samplingspeed: *def_speed
    period: 5